[target.aarch64-linux-android]
ar = "/home/svenschmidt75/Android/Sdk/ndk/21.0.6011959/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-ar"
linker = "/home/svenschmidt75/Android/Sdk/ndk/21.0.6011959/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android26-clang"

[target.armv7-linux-androideabi]
ar = "/home/svenschmidt75/Android/Sdk/ndk/21.0.6011959/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi26-ar"
linker = "/home/svenschmidt75/Android/Sdk/ndk/21.0.6011959/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi26-clang"

[target.i686-linux-android]
ar = "/home/svenschmidt75/Android/Sdk/ndk/21.0.6011959/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android-ar"
linker = "/home/svenschmidt75/Android/Sdk/ndk/21.0.6011959/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android26-clang"
